name: Publish exercises to directory
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Generate exercise-directory.md
        run: |
          python create-exercise-directory.py
          mv exercise-directory.md index.md

      - name: Add Jekyll config
        run: |
          gem install jekyll bundle
          bundle init
          echo 'gem "jekyll"' >> Gemfile
          echo 'gem "no-style-please"' >> Gemfile
          bundle install

      - name: Build Jekyll site
        run: |
          bundle exec jekyll build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./_site
          enable_jekyll: true
